# FROM ubuntu:23.10
FROM python:3.9.17
# copy the whole code
COPY . /digits/
# RUN apt-get update
# RUN apt-get install -y python3 python3-pip
RUN pip3 install -r /digits/requirement.txt
# copy the requirements.txt
# COPY requirements.txt /requirements.tx
# need python
# no need fr conda or venv
# requirements installation

# CMD ["pytest"]
CMD ["echo", "our first cmd line"]